function [tracker] = create_tracker(identifier)

result_directory = fullfile(get_global_variable('directory'), 'results', identifier);

mkpath(result_directory);

if exist(['tracker_' , identifier]) ~= 2 %#ok<EXIST>
    print_debug('WARNING: No configuration for tracker %s found', identifier);
    tracker = struct('identifier', identifier, 'command', [], ...
        'directory', result_directory, 'linkpath', [], ...
        'label', identifier, 'autogenerated', true);
    return;
    %error('Configuration for tracker %s does not exist.', identifier);
end;

tracker_metadata = struct([]);
tracker_label = identifier;
tracker_interpreter = [];
tracker_linkpath = {};
tracker_trax = true;

tracker_configuration = str2func(['tracker_' , identifier]);
tracker_configuration();

tracker_label = strtrim(tracker_label);

tracker = struct('identifier', identifier, 'command', tracker_command, ...
        'directory', result_directory, 'linkpath', {tracker_linkpath}, ...
        'label', tracker_label, 'interpreter', tracker_interpreter, ...
        'autogenerated', false);
    
if tracker_trax
    trax_executable = get_global_variable('trax_client', '');
    if isempty(trax_executable) && ~isempty(tracker.command)
        error('TraX support not available');
    end;
    tracker.run = @trax_wrapper;
    tracker.trax = true;
    tracker.linkpath{end+1} = fullfile(matlabroot, 'bin', lower(computer('arch')));
else
    tracker.run = @system_wrapper; %#ok<UNRCH>
    tracker.trax = false;
end;

performance_filename = fullfile(tracker.directory, 'performance.txt');

if exist(performance_filename, 'file')
    tracker.performance = readstruct(benchmark_hardware(tracker));
end;

if isstruct(tracker_metadata)
    tracker.metadata = tracker_metadata;
end;